development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myapp_development
  host: 127.0.0.1
  pool: 5
  username: root
  password: root
 
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myapp_test
  host: 127.0.0.1
  pool: 5
  username: root
  password: root


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myapp_production
  host: 127.0.0.1
  pool: 5
  username: root
  password: root
