development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myapp_development
  host: 127.0.0.1
  port: 3306
  pool: 5
  username: boby
  password: boby
 
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myapp_test
  host: 127.0.0.1
  port: 3306
  pool: 5
  username: boby
  password: boby


production:
   url: <%= ENV['DATABASE_URL'] %>
